---
# tasks file for bvansomeren.freebsd-nginx

- name: ensure nginx is installed
  package:
    name: "{{ freebsd_nginx_package }}"
    state: present

- name: ensure nginx enabled in rc.conf
  command: sysrc -f /etc/rc.conf nginx_enable=YES

- name: ensure nginx.conf is setup properly
  template:
    src: nginx.conf
    dest: /usr/local/etc/nginx/nginx.conf
  notify: restart nginx

- name: ensure vhost folder exists
  file:
    path: "{{ freebsd_nginx_include_folder }}"
    state: directory

- name: ensure vhost docroot folders exist if requested
  file:
    path: "{{ item.root }}"
    state: directory
  with_items: "{{ freebsd_nginx_vhosts }}"
  when: freebsd_nginx_create_vhosts

- name: ensure vhosts are setup
  template:
    src: vhost.conf
    dest: "{{ freebsd_nginx_include_folder }}/{{ item.server_name }}.conf"
  with_items: "{{ freebsd_nginx_vhosts }}"
  notify: restart nginx

- name: ensure nginx is started
  service:
    name: nginx
    state: started
