---
# tasks file for bvansomeren.freebsd-nginx

- name: ensure nginx is installed
  package:
    name: "{{ freebsd_nginx_package }}"
    state: present

- name: ensure nginx enabled in rc.conf
  command: sysrc -f /etc/rc.conf nginx_enable=YES

- name: ensure nginx.conf is setup properly
  template:
    src: nginx.conf
    dest: "{{ freebsd_nginx_config_folder }}/nginx.conf"
  notify: restart nginx

- name: ensure letsencrypt-acme-challenge.conf is setup
  template:
    src: letsencrypt-acme-challenge.conf
    dest: "{{ freebsd_nginx_config_folder }}/letsencrypt-acme-challenge.conf"
  notify: restart nginx
  when: freebsd_nginx_letsencrypt_enabled

- name: ensure vhost and ssl folders exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ freebsd_nginx_include_folder }}"
  - "{{ freebsd_nginx_ssl_folder }}"

- name: ensure strong dhparam.pem
  command: "openssl dhparam -out {{ freebsd_nginx_ssl_folder }}/dhparam.pem 4096" 
  args:
    creates: "{{ freebsd_nginx_ssl_folder }}/dhparam.pem"

- stat:
    path: "{{ freebsd_nginx_ssl_folder }}/{{ item.server_name }}/cert.pem"
  with_items: "{{ freebsd_nginx_vhosts }}"
  register: certificate_check

- debug:
    var: certificate_check.results

- name: ensure all certificates exists before pushing configuration
  fail:
    msg: "Certificate for doesn't exist at {{ item.stat.path }}"
  when: "{{ not item.stat.exists }}"
  with_items: "{{ certificate_check.results }}"

- name: ensure vhost docroot folders exist if requested
  file:
    path: "{{ item.root }}"
    state: directory
  with_items: "{{ freebsd_nginx_vhosts }}"
  when: freebsd_nginx_create_vhosts

- name: ensure vhosts are setup
  template:
    src: vhost.conf
    dest: "{{ freebsd_nginx_include_folder }}/{{ item.server_name }}.conf"
  with_items: "{{ freebsd_nginx_vhosts }}"
  when: freebsd_nginx_create_vhosts
  notify: restart nginx

- name: ensure nginx is started
  service:
    name: nginx
    state: started

- name: ensure certificate install folders
  file:
    path: "{{ freebsd_nginx_ssl_folder }}/{{ item.server_name }}"
    state: directory
  with_items: "{{ freebsd_nginx_vhosts }}"
  when: freebsd_nginx_letsencrypt_enabled and item.letsencrypt is defined and item.letsencrypt

